spring:
  cloud:
    config:
      server:
        git:
          uri: https://ask@dev.azure.com/hackathon2019/hackathon/_git/configurations
          skipSslValidation: true
          username: ask
          password: newuser123#

server:
  port: 8888

  servlet:
    context-path: /configuration

management:
  endpoints:
    web:
      exposure:
        include: "*"